#=================================================
# https://github.com/kingyan/Actions-Padavan
# Description: Build Padavan With GitHub Actions
# Lisence: MIT
# Author: kingyan
# Build: 2020-02-04 21:08
#=================================================

name: Build PadavanK2P_nano-5.0

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
#    paths:
#      - 'diy.sh'
#    schedule:
#      - cron: 0 8 * * 5
    watch:
      types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev gcc-multilib
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        mkdir -p toolchain-3.4.x
        wget https://github.com/hanwckf/padavan-toolchain/releases/download/v1.0/mipsel-linux-uclibc.tar.xz
        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: K2P_nano-5.0 #K2P_nano K2P_nano-5.0 PSG1218_nano
      run: |
        cd /opt/rt-n56u/trunk
        cp -a configs/boards/PSG1218 configs/boards/K2
        sed -i '5,11d' build_firmware_modify
        sed -i 's/PSG1218/K2/g' configs/templates/PSG1218.config
        sed -i 's/PSG1218/K2/g' configs/templates/PSG1218_nano.config
        sed -i 's/PSG1218/K2/g' configs/boards/K2/board.h
        sed -i 's/PSG1218/K2/g' configs/boards/K2/board.mk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件，按照下面的格式添加即可。
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
        ################################################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件。
        ################################################################################################
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config
        ################################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-K2P_nano-5.0-packages
        path: /opt/images
